name: Check code formatting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    name: Run prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check formatting
        run: npm run format:check
