name: Lint and typecheck
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Tools & Dependencies
        uses: ./.github/actions/install
        with:
          node-version: 16
      - name: Check `*.astro` types
        run: npm run check:astro
      - name: Check `*.ts` types
        run: npm run check:ts
